execute if score mode qr_uid matches 1 run function QR/generator_7
execute if score mode qr_uid matches 2 run function QR/generator_10
execute if score mode qr_uid matches 3 run function QR/generator_15
execute if score mode qr_uid matches 4 run function QR/generator_20
execute if score mode qr_uid matches 5 run function QR/generator_26
execute if score mode qr_uid matches 6 run function QR/generator_18
execute if score mode qr_uid matches 7 run function QR/generator_20
execute if score mode qr_uid matches 8 run function QR/generator_24
execute if score mode qr_uid matches 9 run function QR/generator_30
execute if score mode qr_uid matches 10 run function QR/generator_18
execute if score mode qr_uid matches 11 run function QR/generator_20
execute if score mode qr_uid matches 12 run function QR/generator_24
execute if score mode qr_uid matches 13 run function QR/generator_26
execute if score mode qr_uid matches 14 run function QR/generator_30
execute if score mode qr_uid matches 15 run function QR/generator_22
execute if score mode qr_uid matches 16 run function QR/generator_24
execute if score mode qr_uid matches 17 run function QR/generator_28
execute if score mode qr_uid matches 18 run function QR/generator_30
execute if score mode qr_uid matches 19 run function QR/generator_28
execute if score mode qr_uid matches 20 run function QR/generator_28
execute if score mode qr_uid matches 21 run function QR/generator_28
execute if score mode qr_uid matches 22 run function QR/generator_28
execute if score mode qr_uid matches 23 run function QR/generator_30
execute if score mode qr_uid matches 24 run function QR/generator_30
execute if score mode qr_uid matches 25 run function QR/generator_26
execute if score mode qr_uid matches 26 run function QR/generator_28
execute if score mode qr_uid matches 27 run function QR/generator_30
execute if score mode qr_uid matches 28 run function QR/generator_30
execute if score mode qr_uid matches 29 run function QR/generator_30
execute if score mode qr_uid matches 30 run function QR/generator_30
execute if score mode qr_uid matches 31 run function QR/generator_30
execute if score mode qr_uid matches 32 run function QR/generator_30
execute if score mode qr_uid matches 33 run function QR/generator_30
execute if score mode qr_uid matches 34 run function QR/generator_30
execute if score mode qr_uid matches 35 run function QR/generator_30
execute if score mode qr_uid matches 36 run function QR/generator_30
execute if score mode qr_uid matches 37 run function QR/generator_30
execute if score mode qr_uid matches 38 run function QR/generator_30
execute if score mode qr_uid matches 39 run function QR/generator_30
execute if score mode qr_uid matches 40 run function QR/generator_30
