execute if score "mode" qr_uid matches 14 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_14 ~8~~
execute if score "mode" qr_uid matches 15 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_15 ~8~~
execute if score "mode" qr_uid matches 16 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_16 ~8~~
execute if score "mode" qr_uid matches 17 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_17 ~8~~
execute if score "mode" qr_uid matches 18 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_18 ~8~~
execute if score "mode" qr_uid matches 19 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_19 ~8~~
execute if score "mode" qr_uid matches 20 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_20 ~8~~
execute if score "mode" qr_uid matches 21 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_21 ~8~~
execute if score "mode" qr_uid matches 22 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_22 ~8~~
execute if score "mode" qr_uid matches 23 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_23 ~8~~
execute if score "mode" qr_uid matches 24 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_24 ~8~~
execute if score "mode" qr_uid matches 25 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_25 ~8~~
execute if score "mode" qr_uid matches 26 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_26 ~8~~
execute if score "mode" qr_uid matches 27 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_27 ~8~~
execute if score "mode" qr_uid matches 28 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_28 ~8~~
execute if score "mode" qr_uid matches 29 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_29 ~8~~
execute if score "mode" qr_uid matches 30 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_30 ~8~~
execute if score "mode" qr_uid matches 31 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_31 ~8~~
execute if score "mode" qr_uid matches 32 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_32 ~8~~
execute if score "mode" qr_uid matches 33 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_33 ~8~~
execute if score "mode" qr_uid matches 34 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_34 ~8~~
execute if score "mode" qr_uid matches 35 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_35 ~8~~
execute if score "mode" qr_uid matches 36 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_36 ~8~~
execute if score "mode" qr_uid matches 37 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_37 ~8~~
execute if score "mode" qr_uid matches 38 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_38 ~8~~
execute if score "mode" qr_uid matches 39 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_39 ~8~~
execute if score "mode" qr_uid matches 40 as @e[name=qr_module,scores={qr_prg=1}] at @s run structure load qr_via_40 ~8~~
