execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..3}] if score mode qr_uid matches 14 run scoreboard players set @e[name=qr_main] qr_xor 115
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..5}] if score mode qr_uid matches 15 run scoreboard players set @e[name=qr_main] qr_xor 87
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..5}] if score mode qr_uid matches 16 run scoreboard players set @e[name=qr_main] qr_xor 98
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..1}] if score mode qr_uid matches 17 run scoreboard players set @e[name=qr_main] qr_xor 107
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..5}] if score mode qr_uid matches 18 run scoreboard players set @e[name=qr_main] qr_xor 120
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..3}] if score mode qr_uid matches 19 run scoreboard players set @e[name=qr_main] qr_xor 113
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..3}] if score mode qr_uid matches 20 run scoreboard players set @e[name=qr_main] qr_xor 107
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..4}] if score mode qr_uid matches 21 run scoreboard players set @e[name=qr_main] qr_xor 116
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..2}] if score mode qr_uid matches 22 run scoreboard players set @e[name=qr_main] qr_xor 111
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..4}] if score mode qr_uid matches 23 run scoreboard players set @e[name=qr_main] qr_xor 121
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..6}] if score mode qr_uid matches 24 run scoreboard players set @e[name=qr_main] qr_xor 117
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..8}] if score mode qr_uid matches 25 run scoreboard players set @e[name=qr_main] qr_xor 106
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..10}] if score mode qr_uid matches 26 run scoreboard players set @e[name=qr_main] qr_xor 114
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..8}] if score mode qr_uid matches 27 run scoreboard players set @e[name=qr_main] qr_xor 122
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..3}] if score mode qr_uid matches 28 run scoreboard players set @e[name=qr_main] qr_xor 117
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..7}] if score mode qr_uid matches 29 run scoreboard players set @e[name=qr_main] qr_xor 116
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..5}] if score mode qr_uid matches 30 run scoreboard players set @e[name=qr_main] qr_xor 115
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..13}] if score mode qr_uid matches 31 run scoreboard players set @e[name=qr_main] qr_xor 115
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..17}] if score mode qr_uid matches 32 run scoreboard players set @e[name=qr_main] qr_xor 115
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..17}] if score mode qr_uid matches 33 run scoreboard players set @e[name=qr_main] qr_xor 115
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..13}] if score mode qr_uid matches 34 run scoreboard players set @e[name=qr_main] qr_xor 115
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..12}] if score mode qr_uid matches 35 run scoreboard players set @e[name=qr_main] qr_xor 121
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..6}] if score mode qr_uid matches 36 run scoreboard players set @e[name=qr_main] qr_xor 121
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..17}] if score mode qr_uid matches 37 run scoreboard players set @e[name=qr_main] qr_xor 122
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..4}] if score mode qr_uid matches 38 run scoreboard players set @e[name=qr_main] qr_xor 122
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..20}] if score mode qr_uid matches 39 run scoreboard players set @e[name=qr_main] qr_xor 117
execute as @e[name=qr_main,scores={qr_prg=109}] if entity @e[name=qr_split_sub,scores={qr_code=..19}] if score mode qr_uid matches 40 run scoreboard players set @e[name=qr_main] qr_xor 118
