function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
function QR_new/summon
